language: c

compiler:
  - gcc

env:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release

branches:
 only:
  - Travis_integration

before_install:
 - git submodule update --init --recursive
 - sudo apt-get install libnfsidmap2
 - sudo apt-get install libnfsidmap-dev
 - sudo apt-get install libkrb5-3
 - sudo apt-get install libkrb5-dev
 - sudo apt-get install libk5crypto3
 - sudo apt-get install libgssapi-krb5-2
 - sudo apt-get install libgssglue1
 - sudo apt-get install libdbus-1-3
 - sudo apt-get install dbus
 - sudo apt-get install libdbus-1-dev
 - sudo apt-get install libcap-dev
 - sudo add-apt-repository ppa:semiosis/ubuntu-glusterfs-3.5 -y
 - sudo apt-get update -q
 - sudo apt-get install -y glusterfs-server
 - sudo apt-get install -y xfsprogs

script: mkdir ../build && cd ../build && cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_CONFIG=everything ../nfs-ganesha/src/ && make

notifications:
  email:
    recepients:
      - thomas.favre-bulle@bull.net

    on_success: always
    on_failure: always

