language: c

compiler:
  - gcc

env:
  - BUILD_TYPE=Maintainer
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release

branches:
 only:
  - Travis_integration

before_install:
 - git submodule update --init --recursive
 - sudo apt-get install libnfsidmap2
 - sudo apt-get install libnfsidmap-dev
 - sudo apt-get install libkrb5-3
 - sudo apt-get install libkrb5-dev
 - sudo apt-get install libk5crypto3
 - sudo apt-get install libgssapi-krb5-2
 - sudo apt-get install libgssglue1
 - sudo apt-get install libdbus-1-3
 - sudo apt-get install -y libattr1-dev
 - sudo apt-get install -y libacl1-dev
 - sudo apt-get install dbus
 - sudo apt-get install libdbus-1-dev
 - sudo apt-get install libcap-dev
 - sudo apt-get install -y libjemalloc-dev
 - sudo add-apt-repository -y ppa:gluster/glusterfs-3.6
 - sudo apt-get update -q
 - sudo apt-get install -y glusterfs-common
 - sudo apt-get install -y uuid-dev
 - sudo apt-get install -y libblkid-dev
 - sudo apt-get install -y xfslibs-dev
 - wget -q -O- 'https://ceph.com/git/?p=ceph.git;a=blob_plain;f=keys/release.asc' | sudo apt-key add -
 - echo deb http://eu.ceph.com/debian-dumpling/ $(lsb_release -sc) main | sudo tee /etc/apt/sources.list.d/ceph.list
 - sudo apt-get update -q
 - sudo apt-get install -y libcephfs-dev
 - sudo apt-get install -y samba4-dev
 - sudo apt-get install -y lttng-tools
 - sudo apt-get install -y liblttng-ust-dev
 - sudo apt-get install -y pyqt4-dev-tools
 - sudo apt-get install -y rpm2cpio
 - wget https://downloads.hpdd.intel.com/public/lustre/latest-maintenance-release/el6/server/RPMS/x86_64/lustre-2.5.3-2.6.32_431.23.3.el6_lustre.x86_64.x86_64.rpm -O /tmp/lustre.rpm
 - mkdir /tmp/lustre && pushd /tmp/lustre ; rpm2cpio /tmp/lustre.rpm | cpio -id ./usr/include/\* ./usr/lib64/liblustreapi.a ; popd

script:
 - cd contrib/libzfswrap && aclocal -I m4 && libtoolize --force --copy && autoconf && autoheader && automake -a --add-missing -Wall && ./configure && make && make install
 - mkdir ../build && cd ../build && cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_CONFIG=everything -DUSE_FSAL_PT=ON -DUSE_FSAL_GLUSTER=ON -DUSE_FSAL_CEPH=OFF -DUSE_ADMIN_TOOLS=ON -DUSE_LTTNG=ON -DUSE_TIRPC_IPV6=ON -DLUSTRE_PREFIX=/tmp/lustre/usr ../nfs-ganesha/src/ && make

notifications:
  email:
    recepients:
      - thomas.favre-bulle@bull.net

    on_success: always
    on_failure: always

